import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AsistentePanel from "@/components/Asistente/AsistentePanel";
import BuildBadge from "@/components/BuildBadge";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* Servicio global del Chat IA — se monta una sola vez aquí, en
            el layout raíz, para TODA la aplicación (antes solo vivía en
            app/dashboard/layout.tsx, lo que dejaba fuera "/" y
            "/documentos": abrirPanel() ahí no tenía ningún componente
            real que reaccionara). Un solo AsistentePanel para cualquier
            ruta, nunca duplicado. */}
        <AsistentePanel />
        <BuildBadge />
      </body>
    </html>
  );
}
